-- vim.keymap.set('n', 'V', 'V', { desc = '[V]isual entire line' })
-- vim.keymap.set('n', 'yy', 'yy', { desc = '[Y]ank entire line' })
vim.keymap.set('n', '<A-k>', '<cmd>m .-2<cr>==', { desc = 'Move line up' })
vim.keymap.set('n', '<A-j>', '<cmd>m .+1<CR>==', { desc = 'Move line down' })
vim.keymap.set('v', '<A-j>', "<cmd>'<,'>m '<+1<CR>gv=gv", { desc = 'Move selection down' })
vim.keymap.set('v', '<A-k>', "<cmd>'<,'>m '>-2<CR>gv=gv", { desc = 'Move selection up' })
vim.keymap.set('i', '<A-k>', '<Esc><cmd>m .-2<CR>==gi', { desc = 'Move line up' })
vim.keymap.set('i', '<A-j>', '<Esc><cmd>m .+1<CR>==gi', { desc = 'Move line down' })
