import = [
"~/.config/alacritty/catppuccin-frappe.toml"
    # "~/.config/alacritty/vscode-dark.toml"
]
live_config_reload = true 

[window]
decorations = "none"
startup_mode = "maximized"
option_as_alt = "both"

[font]
size = 13
[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

